data = [
  {
    "type": "attraction",
    "name": "Silver Star",
    "latitude": 48.267746,
    "longitude": 7.720779,
    "area": "Frankreich",
    "minAge": 11,
    "minAgeAdult": 11,
    "minHeight": 140,
    "minHeightAdult": 140
  },
  {
    "type": "attraction",
    "name": "VirtualLine: Euro-Mir",
    "latitude": 48.26511692,
    "longitude": 7.71998618,
    "area": "Russland",
    "minAge": 10,
    "minAgeAdult": 8,
    "minHeight": 130,
    "minHeightAdult": 130
  },
  {
    "type": "attraction",
    "name": "Wasserachterbahn Poseidon",
    "latitude": 48.26657683,
    "longitude": 7.71944295,
    "area": "Griechenland",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "gastronomy",
    "name": "Waffelbäckerei",
    "latitude": 48.267846,
    "longitude": 7.722739,
    "area": "Italien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Taverna Mykonos",
    "latitude": 48.26642581,
    "longitude": 7.71998705,
    "area": "Griechenland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Monorail-Bahn Station \"Luxemburg\"",
    "latitude": 48.264495,
    "longitude": 7.720607,
    "area": "Luxemburg",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Geisterschloss",
    "latitude": 48.26784026,
    "longitude": 7.72196878,
    "area": "Italien",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Schlittenfahrt Schneeflöckchen",
    "latitude": 48.26518754,
    "longitude": 7.72045036,
    "area": "Russland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Josefinas kaiserliche Zauberreise",
    "latitude": 48.263501,
    "longitude": 7.721808,
    "area": "Österreich",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Piraten in Batavia",
    "latitude": 48.26357079,
    "longitude": 7.72040079,
    "area": "Holland",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Eurosat – CanCan Coaster",
    "latitude": 48.267345,
    "longitude": 7.72113,
    "area": "Frankreich",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "attraction",
    "name": "Abenteuer Atlantis",
    "latitude": 48.266235,
    "longitude": 7.72031,
    "area": "Griechenland",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Abenteuerspielplatz",
    "latitude": 48.26125,
    "longitude": 7.722918,
    "area": "Spanien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Donau Dampfer",
    "latitude": 48.26307866,
    "longitude": 7.72271494,
    "area": "Österreich",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Arena of Football - Be Part of It!",
    "latitude": 48.265583,
    "longitude": 7.721263,
    "area": "England",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Atlantica SuperSplash",
    "latitude": 48.262055,
    "longitude": 7.721479,
    "area": "Portugal",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Panoramabahn \"Paddington Station\"",
    "latitude": 48.26526313,
    "longitude": 7.72198224,
    "area": "England",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Panoramabahn Bahnhof \"Spanien\"",
    "latitude": 48.2616,
    "longitude": 7.722934,
    "area": "Spanien",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Panoramabahn Bahnhof \"Russland\"",
    "latitude": 48.265055,
    "longitude": 7.720598,
    "area": "Russland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Ballpool",
    "latitude": 48.263969,
    "longitude": 7.720456,
    "area": "Holland",
    "minAge": 2,
    "minAgeAdult": 2,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Casa da Aventura",
    "latitude": 48.262139,
    "longitude": 7.721784,
    "area": "Portugal",
    "minAge": 3,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "VirtualLine: blue fire Megacoaster",
    "latitude": 48.2620226,
    "longitude": 7.71939634,
    "area": "Island",
    "minAge": 7,
    "minAgeAdult": 7,
    "minHeight": 130,
    "minHeightAdult": 130
  },
  {
    "type": "attraction",
    "name": "Piccolo Mondo",
    "latitude": 48.26744872,
    "longitude": 7.72193018,
    "area": "Italien",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Crazy Taxi",
    "latitude": 48.26553,
    "longitude": 7.722307,
    "area": "England",
    "minAge": 6,
    "minAgeAdult": 3,
    "minHeight": 120,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Liechtensteiner Ballonfahrt",
    "latitude": 48.26591191,
    "longitude": 7.72171306,
    "area": "Liechtenstein",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Elfenfahrt",
    "latitude": 48.267435,
    "longitude": 7.722708,
    "area": "Deutschland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "EP-Express Station \"Alexanderplatz\"",
    "latitude": 48.26888354,
    "longitude": 7.72201145,
    "area": "Deutschland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "EP-Express Station \"Griechenland\"",
    "latitude": 48.266316,
    "longitude": 7.720023,
    "area": "Griechenland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "EP-Express Station \"Spanien\"",
    "latitude": 48.261939,
    "longitude": 7.721789,
    "area": "Spanien",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Euro-Tower",
    "latitude": 48.267138,
    "longitude": 7.721954,
    "area": "Frankreich",
    "minAge": 6,
    "minAgeAdult": null,
    "minHeight": 120,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Feria Swing",
    "latitude": 48.261475,
    "longitude": 7.723023,
    "area": "Spanien",
    "minAge": 10,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Fjord Rafting",
    "latitude": 48.262793,
    "longitude": 7.719901,
    "area": "Skandinavien",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Fluch der Kassandra",
    "latitude": 48.266309,
    "longitude": 7.71955,
    "area": "Griechenland",
    "minAge": 8,
    "minAgeAdult": 5,
    "minHeight": 130,
    "minHeightAdult": 110
  },
  {
    "type": "attraction",
    "name": "Jungfrau-Gletscherflieger",
    "latitude": 48.266884,
    "longitude": 7.720711,
    "area": "Schweiz",
    "minAge": 10,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "attraction",
    "name": "Koffiekopjes",
    "latitude": 48.26389425,
    "longitude": 7.72047363,
    "area": "Holland",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Kolumbusjolle",
    "latitude": 48.261595,
    "longitude": 7.723112,
    "area": "Spanien",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Lada Autodrom",
    "latitude": 48.264771,
    "longitude": 7.720618,
    "area": "Russland",
    "minAge": 4,
    "minAgeAdult": 0,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "London Bus",
    "latitude": 48.26538878,
    "longitude": 7.72230324,
    "area": "England",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Volo da Vinci",
    "latitude": 48.267662,
    "longitude": 7.722291,
    "area": "Italien",
    "minAge": 8,
    "minAgeAdult": 3,
    "minHeight": 130,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Marionetten-Bootsfahrt",
    "latitude": 48.266966,
    "longitude": 7.722999,
    "area": "Deutschland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Matterhorn-Blitz",
    "latitude": 48.266913,
    "longitude": 7.72049,
    "area": "Schweiz",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "attraction",
    "name": "Mini-Scooter",
    "latitude": 48.263763,
    "longitude": 7.72093,
    "area": "Holland",
    "minAge": 3,
    "minAgeAdult": 3,
    "minHeight": 90,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Jim Knopf – Reise durch Lummerland",
    "latitude": 48.267232,
    "longitude": 7.722759,
    "area": "Deutschland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Oldtimer-Fahrt",
    "latitude": 48.267366,
    "longitude": 7.723695,
    "area": "Deutschland",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Panoramabahn Bahnhof \"Deutschland\"",
    "latitude": 48.26796,
    "longitude": 7.723254,
    "area": "Deutschland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Pegasus - Die YoungStar Achterbahn",
    "latitude": 48.267786,
    "longitude": 7.719351,
    "area": "Griechenland",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Fliegender Holländer",
    "latitude": 48.26394581,
    "longitude": 7.72076801,
    "area": "Holland",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Roter Baron",
    "latitude": 48.26407,
    "longitude": 7.721007,
    "area": "Holland",
    "minAge": 3,
    "minAgeAdult": 3,
    "minHeight": 90,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Schweizer Bobbahn",
    "latitude": 48.266435,
    "longitude": 7.721336,
    "area": "Schweiz",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "attraction",
    "name": "Silverstone-Piste",
    "latitude": 48.264853,
    "longitude": 7.72134,
    "area": "England",
    "minAge": 10,
    "minAgeAdult": 3,
    "minHeight": 130,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Wiener Wellenflieger",
    "latitude": 48.26234046,
    "longitude": 7.7229756,
    "area": "Österreich",
    "minAge": 6,
    "minAgeAdult": 4,
    "minHeight": 120,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "The British Carousel",
    "latitude": 48.264753,
    "longitude": 7.721534,
    "area": "England",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Madame Freudenreich Curiosités",
    "latitude": 48.26719018,
    "longitude": 7.72106173,
    "area": "Frankreich",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Vindjammer",
    "latitude": 48.26271,
    "longitude": 7.720726,
    "area": "Skandinavien",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Wasserspielplatz",
    "latitude": 48.263254,
    "longitude": 7.721724,
    "area": "Abenteuerland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Wichtelhausen",
    "latitude": 48.26411,
    "longitude": 7.722967,
    "area": "Grimms Märchenwald",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Laser Adventure - Schule der Abenteurer",
    "latitude": 48.265329,
    "longitude": 7.722128,
    "area": "England",
    "minAge": 10,
    "minAgeAdult": 10,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Kaffi Hús",
    "latitude": 48.26246239,
    "longitude": 7.71926094,
    "area": "Island",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Adventure Food Station",
    "latitude": 48.26344997,
    "longitude": 7.72158945,
    "area": "Abenteuerland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Bayrisch-Badischer Biergarten",
    "latitude": 48.267849,
    "longitude": 7.723921,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Burger Bär",
    "latitude": 48.26857511,
    "longitude": 7.7223652,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Restaurant Schloss Balthasar",
    "latitude": 48.268392,
    "longitude": 7.724973,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Schwarzwälder Vogtshaus",
    "latitude": 48.268426,
    "longitude": 7.723365,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Europa-Park Rock Café",
    "latitude": 48.2685725,
    "longitude": 7.72219303,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "The Three Piglets",
    "latitude": 48.264898,
    "longitude": 7.721859,
    "area": "England",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Arena of Football – Coca-Cola Sportsbar",
    "latitude": 48.265289,
    "longitude": 7.721272,
    "area": "England",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Chez Marianne",
    "latitude": 48.267017,
    "longitude": 7.721303,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Bistro Tomi Ungerer",
    "latitude": 48.267581,
    "longitude": 7.721312,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Crêperie Nadine",
    "latitude": 48.267699,
    "longitude": 7.72113,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Elsässer Holzofenbäckerei",
    "latitude": 48.266843,
    "longitude": 7.721599,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Motorsportsbar",
    "latitude": 48.26764339,
    "longitude": 7.72024222,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Mille Fleurs",
    "latitude": 48.26736553,
    "longitude": 7.72145416,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Petite France",
    "latitude": 48.266889,
    "longitude": 7.722607,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Flammkuchenstand",
    "latitude": 48.266681,
    "longitude": 7.722032,
    "area": "Frankreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Atlantis-Snack",
    "latitude": 48.266092,
    "longitude": 7.720108,
    "area": "Griechenland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Bamboe Baai",
    "latitude": 48.263831,
    "longitude": 7.720152,
    "area": "Holland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Molencafé",
    "latitude": 48.26402542,
    "longitude": 7.72052352,
    "area": "Holland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Friethuys",
    "latitude": 48.26372914,
    "longitude": 7.72064001,
    "area": "Holland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "FoodLoop",
    "latitude": 48.264216,
    "longitude": 7.720833,
    "area": "Luxemburg",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Café Benedetto",
    "latitude": 48.26799789,
    "longitude": 7.72267551,
    "area": "Italien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Gelateria",
    "latitude": 48.267991,
    "longitude": 7.722564,
    "area": "Italien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Mario's Pizza",
    "latitude": 48.2680311,
    "longitude": 7.72289835,
    "area": "Italien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Pizzeria Venezia",
    "latitude": 48.26756692,
    "longitude": 7.721791,
    "area": "Italien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Seehaus",
    "latitude": 48.262815,
    "longitude": 7.722526,
    "area": "Österreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "CMAK - Russian Food & Burger",
    "latitude": 48.265205,
    "longitude": 7.720155,
    "area": "Russland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Coca-Cola Refreshing Station an der Bobbahn",
    "latitude": 48.26605931,
    "longitude": 7.72136303,
    "area": "Schweiz",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Walliser Stuben",
    "latitude": 48.266735,
    "longitude": 7.72099,
    "area": "Schweiz",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Fiskehuset",
    "latitude": 48.263123,
    "longitude": 7.720204,
    "area": "Skandinavien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Fjord Restaurant",
    "latitude": 48.263013,
    "longitude": 7.720095,
    "area": "Skandinavien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Bodega",
    "latitude": 48.261239,
    "longitude": 7.722503,
    "area": "Hotel \"El Andaluz\"",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Don Quichotte",
    "latitude": 48.26129475,
    "longitude": 7.72227065,
    "area": "Hotel \"El Andaluz\"",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "YULLBE GO im blue fire Dome",
    "latitude": 48.262796,
    "longitude": 7.718771,
    "area": "Island",
    "minAge": 8,
    "minAgeAdult": 5,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Whale Adventures - Northern Lights",
    "latitude": 48.26177,
    "longitude": 7.719226,
    "area": "Island",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": 0
  },
  {
    "type": "gastronomy",
    "name": "Casa Atlântica",
    "latitude": 48.262588,
    "longitude": 7.721339,
    "area": "Portugal",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Wackelbrücke mit Wendelrutsche",
    "latitude": 48.26408853,
    "longitude": 7.72083142,
    "area": "Holland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Monorail-Bahn Station \"Island\"",
    "latitude": 48.261982,
    "longitude": 7.719834,
    "area": "Island",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Lítill Island - Hansgrohe Kinderwasserwelt",
    "latitude": 48.261591,
    "longitude": 7.720083,
    "area": "Island",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "VirtualLine: WODAN - Timburcoaster",
    "latitude": 48.26143355,
    "longitude": 7.71899598,
    "area": "Island",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 120,
    "minHeightAdult": 120
  },
  {
    "type": "attraction",
    "name": "Kinderskischule \"Alpin\" & Snow-Tubes",
    "latitude": 48.26300165,
    "longitude": 7.72186919,
    "area": "Österreich",
    "minAge": 6,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Riesen-Weihnachtspyramide",
    "latitude": 48.26644132,
    "longitude": 7.72345667,
    "area": "Irland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Eislauffläche",
    "latitude": 48.26301635,
    "longitude": 7.7193507,
    "area": "Skandinavien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Postamt Himmelspforte",
    "latitude": 48.26505501,
    "longitude": 7.7217018,
    "area": "England",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Weihnachtsmannglühweinstand",
    "latitude": 48.26531933,
    "longitude": 7.72058157,
    "area": "Russland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Bar Glaciar",
    "latitude": 48.261458,
    "longitude": 7.721959,
    "area": "Spanien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Riesenrad \"Bellevue\"",
    "latitude": 48.262384,
    "longitude": 7.721246,
    "area": "Portugal",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "ERDINGER Urweisse Hütt'n",
    "latitude": 48.262564,
    "longitude": 7.721339,
    "area": "Portugal",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Weihnachtsmarkt",
    "latitude": 48.26813137,
    "longitude": 7.72370492,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Jack's DELI",
    "latitude": 48.26399319,
    "longitude": 7.72429066,
    "area": "Königreich der Minimoys",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Poppy Towers",
    "latitude": 48.26412847,
    "longitude": 7.72388692,
    "area": "Königreich der Minimoys",
    "minAge": 6,
    "minAgeAdult": 4,
    "minHeight": 120,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Mül-Müls Karussell",
    "latitude": 48.26418039,
    "longitude": 7.72417125,
    "area": "Königreich der Minimoys",
    "minAge": 4,
    "minAgeAdult": 0,
    "minHeight": 100,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Wurzelrutschen",
    "latitude": 48.26399814,
    "longitude": 7.7243222,
    "area": "Königreich der Minimoys",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Altertümliche Handwerker-Schau",
    "latitude": 48.26657624,
    "longitude": 7.72349133,
    "area": "Irland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Spielplatz Würmchen Wies'n",
    "latitude": 48.262655,
    "longitude": 7.722871,
    "area": "Österreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "SPICES – Küchen der Welt",
    "latitude": 48.26323272,
    "longitude": 7.72122953,
    "area": "Abenteuerland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Quipse Paddle Boats",
    "latitude": 48.266206,
    "longitude": 7.722663,
    "area": "Irland",
    "minAge": 3,
    "minAgeAdult": 3,
    "minHeight": 90,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Tower Tow",
    "latitude": 48.266199,
    "longitude": 7.722692,
    "area": "Irland",
    "minAge": 8,
    "minAgeAdult": 3,
    "minHeight": 130,
    "minHeightAdult": 95
  },
  {
    "type": "attraction",
    "name": "Spinning Dragons",
    "latitude": 48.26630942,
    "longitude": 7.72290385,
    "area": "Irland",
    "minAge": 6,
    "minAgeAdult": 4,
    "minHeight": 120,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "Little Lamb's Land",
    "latitude": 48.26617039,
    "longitude": 7.72297741,
    "area": "Irland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Old Mac Donald's Tractor Fun",
    "latitude": 48.266401,
    "longitude": 7.723051,
    "area": "Irland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Paul's Playboat",
    "latitude": 48.266465,
    "longitude": 7.723354,
    "area": "Irland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Ba-a-a Express",
    "latitude": 48.26623696,
    "longitude": 7.72322337,
    "area": "Irland",
    "minAge": 6,
    "minAgeAdult": 3,
    "minHeight": 120,
    "minHeightAdult": 90
  },
  {
    "type": "attraction",
    "name": "Sheep Rock",
    "latitude": 48.26653038,
    "longitude": 7.72362554,
    "area": "Irland",
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "attraction",
    "name": "Dancing Dingie",
    "latitude": 48.266518,
    "longitude": 7.723905,
    "area": "Irland",
    "minAge": 8,
    "minAgeAdult": 3,
    "minHeight": 130,
    "minHeightAdult": 90
  },
  {
    "type": "gastronomy",
    "name": "The O'Mackay's Café and Pub",
    "latitude": 48.266207,
    "longitude": 7.72356,
    "area": "Irland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Limerick Castle",
    "latitude": 48.2661,
    "longitude": 7.723581,
    "area": "Irland",
    "minAge": 4,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Magellan Lounge",
    "latitude": 48.261927,
    "longitude": 7.721476,
    "area": "Portugal",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "BIG-Bobby-Car Parcours",
    "latitude": 48.266648,
    "longitude": 7.723648,
    "area": "Irland",
    "minAge": 4,
    "minAgeAdult": 1,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "ERDINGER Weißbiergarten",
    "latitude": 48.26259,
    "longitude": 7.722624,
    "area": "Österreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Skitty World Nordic",
    "latitude": 48.262522,
    "longitude": 7.720602,
    "area": "Skandinavien",
    "minAge": 6,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Kinder-Karussell",
    "latitude": 48.26168384,
    "longitude": 7.72198172,
    "area": "Spanien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Melusina Snacks & Drinks",
    "latitude": 48.264513,
    "longitude": 7.721131,
    "area": "Luxemburg",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Voletarium",
    "latitude": 48.269182,
    "longitude": 7.72243004,
    "area": "Deutschland",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "gastronomy",
    "name": "Moby Dick Hot Dogs",
    "latitude": 48.261943,
    "longitude": 7.719914,
    "area": "Island",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Walter's Wurstbude",
    "latitude": 48.26927003,
    "longitude": 7.72230585,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Langnese Happiness Station Voletarium",
    "latitude": 48.26924608,
    "longitude": 7.72222357,
    "area": "Deutschland",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Eurosat Coastiality",
    "latitude": 48.26748407,
    "longitude": 7.72055613,
    "area": "Frankreich",
    "minAge": 14,
    "minAgeAdult": 14,
    "minHeight": 130,
    "minHeightAdult": 130
  },
  {
    "type": "attraction",
    "name": "EP-Express Station \"Hotels\"",
    "latitude": 48.26056,
    "longitude": 7.722623,
    "area": null,
    "minAge": 6,
    "minAgeAdult": 0,
    "minHeight": 120,
    "minHeightAdult": 0
  },
  {
    "type": "gastronomy",
    "name": "Pastaria di Enzo",
    "latitude": 48.2677109,
    "longitude": 7.72187086,
    "area": "Italien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "granini Saft Butikk",
    "latitude": 48.2634,
    "longitude": 7.720887,
    "area": "Skandinavien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Tiroler Jausenstandl",
    "latitude": 48.263,
    "longitude": 7.722003,
    "area": "Österreich",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "Snorri Touren",
    "latitude": 48.26286332,
    "longitude": 7.72016747,
    "area": "Skandinavien",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": 130,
    "minHeightAdult": 0
  },
  {
    "type": "gastronomy",
    "name": "Is Huset",
    "latitude": 48.263343,
    "longitude": 7.720663,
    "area": "Skandinavien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Magnum Pleasure Store",
    "latitude": 48.26219039,
    "longitude": 7.71946511,
    "area": "Island",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "blue fire Megacoaster",
    "latitude": 48.26276298,
    "longitude": 7.71881572,
    "area": "Island",
    "minAge": 7,
    "minAgeAdult": 7,
    "minHeight": 130,
    "minHeightAdult": 130
  },
  {
    "type": "attraction",
    "name": "WODAN - Timburcoaster",
    "latitude": 48.26167104,
    "longitude": 7.71856683,
    "area": "Island",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "attraction",
    "name": "Euro-Mir",
    "latitude": 48.26506782,
    "longitude": 7.72018199,
    "area": "Russland",
    "minAge": 8,
    "minAgeAdult": 8,
    "minHeight": 130,
    "minHeightAdult": 130
  },
  {
    "type": "attraction",
    "name": "ARTHUR",
    "latitude": 48.26379411,
    "longitude": 7.72375497,
    "area": "Königreich der Minimoys",
    "minAge": 6,
    "minAgeAdult": 4,
    "minHeight": 120,
    "minHeightAdult": 100
  },
  {
    "type": "gastronomy",
    "name": "The Baltic - Coffee & Lounge",
    "latitude": 48.26286146,
    "longitude": 7.7186902,
    "area": "Island",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "VirtualLine: Piraten in Batavia",
    "latitude": 48.26371636,
    "longitude": 7.7203537,
    "area": "Holland",
    "minAge": 8,
    "minAgeAdult": 0,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Flammlachsstand",
    "latitude": 48.26195254,
    "longitude": 7.71954674,
    "area": "Island",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "Walliser Weinkeller",
    "latitude": 48.2666368,
    "longitude": 7.72127566,
    "area": "Schweiz",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "WinterWunderWelt",
    "latitude": 48.26155446,
    "longitude": 7.72180644,
    "area": "Spanien",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "attraction",
    "name": "VirtualLine: Voletarium",
    "latitude": 48.26919271,
    "longitude": 7.72239651,
    "area": "Deutschland",
    "minAge": 8,
    "minAgeAdult": 4,
    "minHeight": 130,
    "minHeightAdult": 100
  },
  {
    "type": "attraction",
    "name": "VirtualLine: Wasserachterbahn Poseidon",
    "latitude": 48.26650006,
    "longitude": 7.71927665,
    "area": "Griechenland",
    "minAge": 8,
    "minAgeAdult": 6,
    "minHeight": 130,
    "minHeightAdult": 120
  },
  {
    "type": "gastronomy",
    "name": "Spirello-Kartoffel-Hüüs",
    "latitude": 48.26621724,
    "longitude": 7.72127303,
    "area": "Schweiz",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  },
  {
    "type": "gastronomy",
    "name": "DELI Refresh – Ice&Drinks",
    "latitude": 48.2639548,
    "longitude": 7.72397952,
    "area": "Königreich der Minimoys",
    "minAge": null,
    "minAgeAdult": null,
    "minHeight": null,
    "minHeightAdult": null
  }
]
